### ISSUE TITLE
Misleading/wrong tests?

### ISSUE THREAD

**Issue by Xcelled** [pypa/bandersnatch#58] opened 2018-10-18 02:19 UTC
I might be missing something here, but I'm noticing a lot of tests use this "pattern":

```python
def test_mirror_sync_package_error_no_early_exit(mirror, requests):
    mirror.master.all_packages = mock.Mock()
    mirror.master.all_packages.return_value = {"foo": 1}

   # test code
```

It's mocking a nonexistent method. I removed the lines and the tests still pass. It's weird and also doesn't give me a lot of confidence in the test suite being useful, especially when considering that the code coverage reports that all of the bandersnatch classes are completely uncovered. I know they're not, but it's confusing to say the least:

![image](https://user-images.githubusercontent.com/5599341/47127304-9eecaa80-d25a-11e8-857f-9aa993ef55f0.png)

**Comment by cooperlees** [comment] 2018-10-18 14:38
Hmm - this use to show coverage when I last looked in depth (when I Python 3’d the code). I’ll try look into it. But if you work it out PRs will be accepted.

**Comment by cooperlees** [comment] 2018-10-18 14:57
I get slightly different results running tox (from trunk/HEAD) and then looking at the coverage HTML output. Have attached screenshot. But there are some files there I’d expect some coverage that says 0%.
![4ecd3365-ca10-4dd7-b897-c346f7209743](https://user-images.githubusercontent.com/3005596/47163643-0ab32f80-d2bc-11e8-89ee-0fd6ead88228.png)

How I ran (from root of bandersnatch repo):
```
python3 -m venv /tmp/tb
/tmp/tb/bin/pip install —upgrade pip setuptools tox
/tmp/tb/bin/tox
```

**Comment by cooperlees** [comment] 2018-10-18 15:54
Put up #63 To address this. Then we can look into the mocking issues ...

**Comment by yeraydiazdiaz** [comment] 2018-10-27 15:31
I can't reproduce this issue, `all_packages` is defined in [`master.py`](https://github.com/pypa/bandersnatch/blob/master/src/bandersnatch/master.py#L94) and commenting the mock above does break the test

**Comment by cooperlees** [comment] 2018-10-27 17:16
Thanks for trying to repro and noting this. If I get some time I'll try repro and if I can't I will close this issue. Also, if anyone else can try repro unmocking somethings etc. that would be great!

**Comment by Xcelled** [comment] 2018-10-27 19:41
Wow I have no idea how I missed it. It's *right there*.

Removing the mock didn't break the tests for me, but it's possible something else was going on anyway.

**Comment by cooperlees** [comment] 2018-11-20 01:15
I'm confident these work.

**Closed by cooperlees** 2018-11-20 01:15 UTC
Labels: bug, help wanted
